(() => {
  "use strict";
  const scripts=[["example_combined_environment","串行运行两个已注册环境"],["example_console_environment","Telnet 自动检测与 Ctrl+B 响应"],["example_host_environment","SSH 下载、解包、上传与执行"],["unions_v100_run_udk","UnionS SDK / Ubengine UDK 安装"]];
  const prompts=[["SSH udk_host host","141.131.72.175","目标 SSH 地址 · Enter 使用默认值"],["SSH udk_host port","22","1–65535 · Enter 使用默认值"],["SSH udk_host username","root","远端登录用户"],["SSH udk_host password","","密码不会显示在输出与日志中","password"],["SSH udk_host connect_timeout","10.0","连接超时，单位秒"],["Package UnionS_SDK_Drv remote directory","","Enter 沿用上次路径 · !newest 使用 config.json automatic newest"]];
  const state={selected:3,mode:"run",running:false,autoScroll:true,prompt:0,timer:null,lines:[],waiting:false,external:false};
  const $=id=>document.getElementById(id);const ids=["scriptList","modeSwitch","packagePolicy","runBtn","stopBtn","terminal","promptCard","promptLabel","promptInput","promptHelp","promptStep","filterInput","scrollBtn","clearBtn","exportBtn","toast"];
  const el=Object.fromEntries(ids.map(id=>[id,$(id)]));const escapeHtml=v=>String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));const stamp=()=>new Date().toISOString().replace("Z","+08:00");
  function highlighted(raw){const t=escapeHtml(raw);const tokens=/(\[\d{4}-\d\d-\d\dT[^\]]+\])|(EOF during negotiation|SSH_PROTOCOL_ERROR|protocol_error|FAILED|failure|failed|ERROR|error)|(SUCCESS|success|completed|ONLINE|verified=yes|md5_verified=True)|(WARNING|warning|timeout|DISCONNECTED|UNKNOWN|result_unknown)|(!newest|Ctrl\+B|KEYWORD|automatic newest)|\b([a-f0-9]{32})\b|((?:[A-Za-z]:\\|\/)[^\s,&quot;{}]+)/gi;return t.replace(tokens,(m,time,bad,ok,warn,key,md5,path)=>`<span class="${time?"hl-time":bad?"hl-bad":ok?"hl-ok":warn?"hl-warn":key?"hl-key":md5?"hl-md5":"hl-path"}">${m}</span>`)}
  function applyFilter(n){const q=el.filterInput.value.trim().toLowerCase();n.classList.toggle("hidden",!!q&&!(n.dataset.raw||"").toLowerCase().includes(q))}function add(text="",kind=""){state.lines.push(String(text));const n=document.createElement("div");n.className=`line ${kind}`;n.dataset.raw=String(text);n.innerHTML=highlighted(text);applyFilter(n);el.terminal.appendChild(n);if(state.autoScroll)el.terminal.scrollTop=el.terminal.scrollHeight}const log=(msg,kind="")=>add(`[${stamp()}] ${msg}`,kind);const gap=()=>add("","break");
  function later(fn,ms=400){clearTimeout(state.timer);state.timer=setTimeout(()=>state.running&&fn(),ms)}function toast(msg){el.toast.textContent=msg;el.toast.classList.add("show");setTimeout(()=>el.toast.classList.remove("show"),1600)}
  function renderScripts(){el.scriptList.innerHTML=scripts.map((s,i)=>`<button class="script-card ${i===state.selected?"active":""}" data-index="${i}"><span class="script-id">${String(i+1).padStart(2,"0")}</span><span><span class="script-name">${escapeHtml(s[0])}</span><span class="script-desc">${escapeHtml(s[1])}</span></span><span class="chev">›</span></button>`).join("")}
  function showPrompt(index){state.prompt=index;state.waiting=true;state.external=false;const p=prompts[index];el.promptStep.textContent=`${String(index+1).padStart(2,"0")} / ${String(prompts.length).padStart(2,"0")}`;el.promptLabel.textContent=p[0];el.promptInput.type=p[3]||"text";el.promptInput.value=index===5&&el.packagePolicy.value==="!newest"?"!newest":p[1];el.promptInput.placeholder=p[1]?`default: ${p[1]}`:"输入值或直接回车";el.promptHelp.textContent=p[2];el.promptCard.classList.add("visible");setTimeout(()=>el.promptInput.focus(),20)}
  function showExternalPrompt(p){state.waiting=true;state.external=true;state.externalData=p;const label=p.label||"Input required";const newest=/^Package\s/i.test(label)&&el.packagePolicy.value==="!newest";el.promptStep.textContent="LIVE";el.promptLabel.textContent=label;el.promptInput.type=p.secret?"password":"text";el.promptInput.value=newest?"!newest":(p.default||"");el.promptInput.placeholder=p.default?`default: ${p.default}`:"输入值或直接回车";el.promptHelp.textContent=newest?"已选择 config.json automatic newest；Enter 提交 !newest":(p.help||"Enter 使用提示中的默认值");el.promptCard.classList.add("visible");setTimeout(()=>el.promptInput.focus(),20)}
  function submitPrompt(){if(!state.running||!state.waiting)return;const value=el.promptInput.value.trim();if(state.external){const p=state.externalData||{};add(`${p.label||"Input"} → ${p.secret?"******":(value||p.default||"<default>")}`,"command");state.waiting=false;el.promptCard.classList.remove("visible");if(window.AutoEnvBridge&&typeof window.AutoEnvBridge.submitPrompt==="function")Promise.resolve(window.AutoEnvBridge.submitPrompt(value)).catch(error=>{add(`LOCAL BRIDGE INPUT ERROR: ${error.message||error}`,"system");finish(false)});return}const p=prompts[state.prompt];add(`${p[0]} → ${p[3]==="password"?"******":(value||p[1]||"<default>")}`,"command");state.waiting=false;el.promptCard.classList.remove("visible");if(state.prompt+1<prompts.length)later(()=>showPrompt(state.prompt+1),180);else later(runOperations,260)}
  function block(title,lines,ok=true){gap();log(`=== ${title} [${ok?"SUCCESS":"FAILED"}] ===`,"system");lines.forEach(x=>add(`  ${x}`));gap()}
  function runOperations(){log("PACKAGE PATH name=UnionS_SDK_Drv mode=base_link_newest override=None","system");later(()=>{block("DOWNLOAD",["operation_id: 0001","package: UnionS_SDK_Drv","source: /compilepackage/CI_Version/torino/br_hisi_trunk_ai/202607/20260717_newest/HN922-driver.aarch64.run","destination: D:\\AutoEnv\\logs\\current\\packages\\HN922-driver.aarch64.run","result: status=success size=1441257 duration_ms=344","md5: cc613b7752e54fe830462a2eeb4fe1ad"]);later(()=>{block("SCP UPLOAD",["operation_id: 0002","target: SCP udk_host","source: D:\\AutoEnv\\logs\\current\\packages\\HN922-driver.aarch64.run","destination: /root/autoEnv/HN922-driver.aarch64.run","result: status=success duration_ms=742","md5: verified=yes local=cc613b7752e54fe830462a2eeb4fe1ad remote=cc613b7752e54fe830462a2eeb4fe1ad"]);later(()=>{log("SSH udk_host STDOUT installing UDK package...","system");log("SSH udk_host STDOUT [  OK  ] driver loaded");log("SSH udk_host STDOUT Press Ctrl+B to enter maintenance mode");log("SSH udk_host STDOUT KEYWORD matched · response bytes 0x02 sent","system");later(()=>{block("SSH EXECUTE",["operation_id: 0003","target: SSH udk_host","command:","  bash /root/autoEnv/udk_install.sh","result: status=success phase=complete exit_code=0 duration_ms=3251"]);finish(true)},600)},620)},620)},620)}
  function start(){if(state.running)return;state.running=true;state.prompt=0;el.runBtn.disabled=true;el.stopBtn.disabled=false;gap();log("=== SCRIPT START ===","system");add(`  name: ${scripts[state.selected][0]}`);add(`  mode: ${state.mode}`);add(`  bridge: ${window.AutoEnvBridge?"local":"demo"}`);gap();if(window.AutoEnvBridge&&typeof window.AutoEnvBridge.run==="function")Promise.resolve(window.AutoEnvBridge.run({script:scripts[state.selected][0],mode:state.mode,packagePolicy:el.packagePolicy.value,onOutput:line=>add(line),onPrompt:showExternalPrompt,onComplete:r=>finish(!!(r&&r.success))})).catch(error=>{add(`LOCAL BRIDGE START ERROR: ${error.message||error}`,"system");finish(false)});else if(state.mode==="rerun")later(runOperations,350);else later(()=>showPrompt(0),280)}
  function finish(ok){state.running=false;state.waiting=false;clearTimeout(state.timer);el.promptCard.classList.remove("visible");el.runBtn.disabled=false;el.stopBtn.disabled=true;block("SCRIPT END",[`name: ${scripts[state.selected][0]}`,`status: ${ok?"success":"aborted"}`,"run_dir: D:\\AutoEnv\\logs\\current"],ok)}function stop(){if(!state.running)return;if(window.AutoEnvBridge&&typeof window.AutoEnvBridge.stop==="function")window.AutoEnvBridge.stop();clearTimeout(state.timer);log("ABORT requested by operator","system");finish(false)}
  el.scriptList.addEventListener("click",e=>{const c=e.target.closest(".script-card");if(c&&!state.running){state.selected=Number(c.dataset.index);renderScripts()}});el.modeSwitch.addEventListener("click",e=>{const b=e.target.closest("button[data-mode]");if(b&&!state.running){state.mode=b.dataset.mode;[...el.modeSwitch.children].forEach(x=>x.classList.toggle("active",x===b))}});el.runBtn.addEventListener("click",start);el.stopBtn.addEventListener("click",stop);el.promptCard.addEventListener("submit",e=>{e.preventDefault();submitPrompt()});
  el.filterInput.addEventListener("input",()=>[...el.terminal.children].forEach(n=>{n.innerHTML=highlighted(n.dataset.raw||"");applyFilter(n)}));el.scrollBtn.addEventListener("click",()=>{state.autoScroll=!state.autoScroll;el.scrollBtn.classList.toggle("active",state.autoScroll);el.scrollBtn.textContent=state.autoScroll?"AUTO-SCROLL":"SCROLL LOCK"});el.clearBtn.addEventListener("click",()=>{state.lines=[];el.terminal.innerHTML="";toast("OUTPUT CLEARED")});el.exportBtn.addEventListener("click",()=>{const blob=new Blob([state.lines.join("\n")],{type:"text/plain;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`autoenv-${Date.now()}.log`;a.click();URL.revokeObjectURL(a.href);toast("LOG EXPORTED")});document.addEventListener("keydown",e=>{if(e.key==="Escape")stop();if(e.ctrlKey&&e.key==="Enter"){e.preventDefault();state.waiting?submitPrompt():start()}});
  function loadBridge(){if(!window.AutoEnvBridge)return;$("bridgeLabel").textContent="LOCAL BRIDGE";if(typeof window.AutoEnvBridge.listScripts==="function")window.AutoEnvBridge.listScripts().then(items=>{if(!Array.isArray(items)||!items.length)return;scripts.splice(0,scripts.length,...items.map(item=>[item.name,item.description||"Registered AutoEnv script"]));state.selected=Math.min(state.selected,scripts.length-1);renderScripts();const count=document.querySelector(".count");if(count)count.textContent=`${String(scripts.length).padStart(2,"0")} ONLINE`}).catch(error=>add(`Bridge script discovery failed: ${error.message||error}`,"system"))}
  window.addEventListener("autoenv-bridge-ready",loadBridge);setInterval(()=>$("clock").textContent=new Date().toLocaleTimeString("zh-CN",{hour12:false}),1000);loadBridge();renderScripts();add("AutoEnv Control Plane / interface ready","system");add("Select an environment script, then initialize run.","dim");add("Keyword highlighter armed: SUCCESS · FAILED · Ctrl+B · paths · MD5","dim");
})();
