(() => {
  "use strict";
  const state={envs:[],scripts:[],tools:[],selectedEnv:null,selectedTool:null,runCursor:0,agentCursor:0,runTimer:null,agentTimer:null};
  const $=id=>document.getElementById(id); const $$=s=>[...document.querySelectorAll(s)];
  const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  async function api(path,options={}){const r=await fetch(path,options);const value=await r.json();if(!r.ok)throw new Error(value.error||`${r.status}`);return value}
  const post=(path,value)=>api(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(value)});
  function toast(message){const n=$("toast");n.textContent=message;n.classList.add("show");setTimeout(()=>n.classList.remove("show"),2200)}
  $$("#tabs button").forEach(button=>button.onclick=()=>{$$("#tabs button").forEach(x=>x.classList.toggle("active",x===button));$$('.page').forEach(x=>x.classList.toggle("active",x.id===`page-${button.dataset.page}`))});

  function connectionRow(type,value={}){const n=document.createElement("div");n.className=`repeat-row ${type}`;const common=`<input data-key="name" placeholder="逻辑名" value="${esc(value.name||"")}"><input data-key="host" placeholder="IP / Host" value="${esc(value.host||"")}">`;
    if(type==="telnet")n.innerHTML=common+`<input data-key="port" title="Telnet 端口" type="number" value="${esc(value.port??23)}"><input data-key="baud_rate" title="串口频率/波特率" type="number" value="${esc(value.baud_rate??115200)}"><input data-key="timeout" title="超时秒数" type="number" value="${esc(value.timeout??30)}"><select data-key="shell_mode"><option>auto</option><option>posix</option><option>prompt</option></select><button type="button" class="remove">×</button>`;
    else n.innerHTML=common+`<input data-key="port" type="number" value="${esc(value.port??(type==="ftp"?21:22))}"><input data-key="username" placeholder="用户名" value="${esc(value.username||"root")}"><input data-key="password" type="password" placeholder="密码" value="${esc(value.password||"")}"><input data-key="${type==="ftp"?"timeout":"connect_timeout"}" type="number" value="${esc(value[type==="ftp"?"timeout":"connect_timeout"]??30)}"><button type="button" class="remove">×</button>`;
    n.querySelector(".remove").onclick=()=>n.remove(); return n;
  }
  function addRow(container,type,value){$(container).append(connectionRow(type,value))}
  $("addSsh").onclick=()=>addRow("sshRows","ssh");$("addTelnet").onclick=()=>addRow("telnetRows","telnet");$("addFtp").onclick=()=>addRow("ftpRows","ftp");
  function rows(id){return [...$(id).children].map(row=>Object.fromEntries([...row.querySelectorAll("[data-key]")].map(input=>[input.dataset.key,input.type==="number"?Number(input.value):input.value]))).filter(x=>x.name&&x.host)}
  function blankEnv(){const f=$("environmentForm");f.reset();$("sshRows").innerHTML="";$("telnetRows").innerHTML="";$("ftpRows").innerHTML="";addRow("sshRows","ssh");addRow("telnetRows","telnet");state.selectedEnv=null}
  $("newEnvironment").onclick=blankEnv;
  function editEnv(env){state.selectedEnv=env.name;const f=$("environmentForm");f.name.value=env.name||"";f.title.value=env.title||"";$("sshRows").innerHTML="";$("telnetRows").innerHTML="";$("ftpRows").innerHTML="";Object.entries(env.ssh_hosts||{}).forEach(([name,v])=>addRow("sshRows","ssh",{name,...v}));Object.entries(env.telnet_connections||{}).forEach(([name,v])=>addRow("telnetRows","telnet",{name,...v}));Object.entries(env.ftp_hosts||{}).forEach(([name,v])=>addRow("ftpRows","ftp",{name,...v}));renderEnvs()}
  function objectByName(items){return Object.fromEntries(items.map(({name,...rest})=>[name,rest]))}
  $("environmentForm").onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;const value={name:f.name.value.trim(),title:f.title.value.trim(),ssh_hosts:objectByName(rows("sshRows")),telnet_connections:objectByName(rows("telnetRows")),ftp_hosts:objectByName(rows("ftpRows"))};await post("/api/environments",value);$("envSaveState").textContent="已保存";toast("环境 JSON 已保存");await loadEnvs();editEnv(value)};
  function renderEnvs(){$("environmentList").innerHTML=state.envs.length?state.envs.map(env=>`<button class="env-card ${state.selectedEnv===env.name?"active":""}" data-name="${esc(env.name)}"><strong>${esc(env.title||env.name)}</strong><span>${esc(env.name)} · ${Object.keys(env.ssh_hosts||{}).length} 网口 · ${Object.keys(env.telnet_connections||{}).length} 串口</span></button>`).join(""):`<div class="empty">还没有环境档案</div>`;$$('.env-card').forEach(n=>n.onclick=()=>editEnv(state.envs.find(x=>x.name===n.dataset.name)))}
  async function loadEnvs(){state.envs=(await api("/api/environments")).environments;renderEnvs();$("launchEnvironment").innerHTML=`<option value="">选择环境</option>`+state.envs.map(x=>`<option value="${esc(x.name)}">${esc(x.title||x.name)}</option>`).join("")}

  async function loadScripts(){state.scripts=(await api("/api/scripts")).scripts;$("launchScript").innerHTML=`<option value="">选择脚本</option>`+state.scripts.map(x=>`<option value="${esc(x.name)}">${esc(x.name)} — ${esc(x.description)}</option>`).join("")}
  function renderScriptFields(){const script=state.scripts.find(x=>x.name===$("launchScript").value);$("packageFields").innerHTML=(script?.packages||[]).map(name=>`<label>包 ${esc(name)}<input data-package="${esc(name)}" placeholder="留空：默认最新包；填写：指定 HDFS 链接"></label>`).join("");$("argumentFields").innerHTML=(script?.parameters||[]).map(field=>`<label>${esc(field.label||field.name)}<input data-argument="${esc(field.name)}" ${field.required?"required":""} placeholder="${esc(field.placeholder||"")}"></label>`).join("")}
  $("launchScript").onchange=renderScriptFields;
  function addLine(container,text){const line=document.createElement("div");line.className="line";line.dataset.raw=text;line.innerHTML=esc(text).replace(/(success|completed|verified|ready)/ig,'<span class="ok">$1</span>').replace(/(failed|error|exception)/ig,'<span class="bad">$1</span>').replace(/(warning|timeout)/ig,'<span class="warn">$1</span>').replace(/([A-Za-z]:\\[^\s]+|\/[^\s]+)/g,'<span class="path">$1</span>');container.append(line);container.scrollTop=container.scrollHeight}
  async function poll(kind){const isRun=kind==="run",cursorKey=isRun?"runCursor":"agentCursor",container=$(isRun?"console":"agentConsole");try{const data=await api(`/api/${kind}/events?cursor=${state[cursorKey]}`);state[cursorKey]=data.next;for(const event of data.events){if(event.type==="output")addLine(container,event.text);if(event.type==="complete"){addLine(container,`[${event.success?"SUCCESS":"FAILED"}] ${event.status}`);return}}state[isRun?"runTimer":"agentTimer"]=setTimeout(()=>poll(kind),180)}catch(error){addLine(container,`BRIDGE ERROR: ${error.message}`)}}
  $("launchForm").onsubmit=async e=>{e.preventDefault();const packages=Object.fromEntries($$("[data-package]").map(n=>[n.dataset.package,n.value.trim()?{path_override:n.value.trim()}:{}]));const arguments_=Object.fromEntries($$("[data-argument]").map(n=>[n.dataset.argument,n.value]));const request={script:$("launchScript").value,mode:$("launchMode").value,environment:$("launchEnvironment").value,parameters:{packages,arguments:arguments_}};$("console").innerHTML="";state.runCursor=0;await post("/api/run/start",request);poll("run")};
  $("stopRun").onclick=()=>post("/api/run/stop",{});$("openLog").onclick=()=>post("/api/open",{target:"log"}).catch(e=>toast(e.message));$("openRun").onclick=()=>post("/api/open",{target:"run"}).catch(e=>toast(e.message));$("clearConsole").onclick=()=>$("console").innerHTML="";$("consoleFilter").oninput=e=>$$('#console .line').forEach(n=>n.classList.toggle("hidden",!n.dataset.raw.toLowerCase().includes(e.target.value.toLowerCase())));

  async function loadTools(){state.tools=(await api("/api/tools")).tools;renderToolNav();if(state.tools[0])selectTool(state.tools[0].name)}
  function renderToolNav(){$("toolNav").innerHTML=state.tools.map(x=>`<button class="tool-link ${x.name===state.selectedTool?"active":""}" data-name="${esc(x.name)}"><strong>${esc(x.title)}</strong><span>${esc(x.description)}</span></button>`).join("");$$('.tool-link').forEach(n=>n.onclick=()=>selectTool(n.dataset.name))}
  function toolControl(field){const a=`data-name="${esc(field.name)}" ${field.required?"required":""}`;if(field.type==="textarea")return `<textarea ${a} placeholder="${esc(field.placeholder||"")}">${esc(field.default||"")}</textarea>`;if(field.type==="select")return `<select ${a}>${(field.options||[]).map(option=>`<option value="${esc(typeof option==="object"?option.value:option)}">${esc(typeof option==="object"?option.label:option)}</option>`).join("")}</select>`;if(field.type==="checkbox")return `<input ${a} type="checkbox" ${field.default?"checked":""}>`;return `<input ${a} type="${esc(field.type||"text")}" value="${esc(field.default||"")}" placeholder="${esc(field.placeholder||"")}">`}
  function selectTool(name){state.selectedTool=name;renderToolNav();const tool=state.tools.find(x=>x.name===name);$("toolStage").innerHTML=`<span class="kicker">DYNAMIC PYTHON TOOL</span><h2>${esc(tool.title)}</h2><p class="muted">${esc(tool.description)}</p><form class="tool-form" id="activeToolForm">${tool.fields.map(field=>`<label>${esc(field.label||field.name)}${toolControl(field)}</label>`).join("")}<button class="primary">运行工具</button></form><pre class="tool-result" id="toolResult">等待执行</pre>`;$("activeToolForm").onsubmit=async e=>{e.preventDefault();const values=Object.fromEntries([...e.currentTarget.querySelectorAll("[data-name]")].map(n=>[n.dataset.name,n.type==="checkbox"?n.checked:n.type==="number"?Number(n.value):n.value]));try{$("toolResult").textContent=JSON.stringify((await post("/api/tools/run",{name,values})).result,null,2)}catch(error){$("toolResult").textContent=`ERROR: ${error.message}`}}}

  async function loadSettings(){const s=await api("/api/settings");$("uploadDir").value=s.upload_dir||"";$("agentCommand").value=s.agent_command||"codeagent"}
  $("agentSettings").onclick=()=>$("settingsPanel").classList.toggle("open");$("saveSettings").onclick=async()=>{await post("/api/settings",{upload_dir:$("uploadDir").value,agent_command:$("agentCommand").value});toast("Agent 设置已保存")};
  async function uploadFiles(files){for(const file of files){const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)});const saved=await post("/api/upload",{name:file.name,data});const prefix=file.type.startsWith("image/")?"请查看图片":"请解析并按 AutoEnv Web Tool 契约注册这个文件";$("agentInput").value+=`${$("agentInput").value?"\n":""}${prefix}: ${saved.path}`;toast(`${file.name} 已保存`)}}
  const dz=$("dropzone");dz.onclick=()=>$("agentFiles").click();$("agentFiles").onchange=e=>uploadFiles(e.target.files).catch(x=>toast(x.message));["dragenter","dragover"].forEach(t=>dz.addEventListener(t,e=>{e.preventDefault();dz.classList.add("drag")}));["dragleave","drop"].forEach(t=>dz.addEventListener(t,e=>{e.preventDefault();dz.classList.remove("drag")}));dz.addEventListener("drop",e=>uploadFiles(e.dataTransfer.files).catch(x=>toast(x.message)));
  $("agentStart").onclick=async()=>{$("agentConsole").innerHTML="";state.agentCursor=0;await post("/api/agent/start",{command:$("agentCommand").value});poll("agent")};$("agentStop").onclick=()=>post("/api/agent/stop",{});$("agentInputForm").onsubmit=async e=>{e.preventDefault();const value=$("agentInput").value;if(!value)return;await post("/api/agent/input",{value});$("agentInput").value=""};

  Promise.all([api("/api/health"),loadEnvs(),loadScripts(),loadTools(),loadSettings()]).then(()=>{$("health").textContent="LOCAL BRIDGE ONLINE";blankEnv()}).catch(error=>{$("health").textContent="BRIDGE ERROR";toast(error.message)});
})();
