(() => {
  "use strict";
  const state={envs:[],scripts:[],resourceLabels:[],tools:[],selectedEnv:null,selectedTool:null,runCursor:0,agentCursor:0,toolCursor:0,runTimer:null,agentTimer:null,toolTimer:null,toolGeneration:0,agentPollGeneration:0,agentSessionGeneration:0,terminal:null,agentRunning:false,logBatches:[],selectedLogBatch:"",logTargets:[],logPanes:[],logFinds:[],logContexts:[],logFindTimers:{},logQuerySerial:0,logQueryTokens:[]};
  const $=id=>document.getElementById(id); const $$=s=>[...document.querySelectorAll(s)];
  const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  async function api(path,options={}){const r=await fetch(path,options);const value=await r.json();if(!r.ok)throw new Error(value.error||`${r.status}`);return value}
  const post=(path,value)=>api(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(value)});
  function toast(message){const n=$("toast");n.textContent=message;n.classList.add("show");setTimeout(()=>n.classList.remove("show"),2200)}
  $$("#tabs button").forEach(button=>button.onclick=()=>{$$("#tabs button").forEach(x=>x.classList.toggle("active",x===button));$$('.page').forEach(x=>x.classList.toggle("active",x.id===`page-${button.dataset.page}`))});

  function labelsFor(type){const kind=type==="telnet"?"serial":"network";return state.resourceLabels.filter(x=>x.kind===kind)}
  function labelOptions(type,selected){const labels=labelsFor(type),missing=selected&&!labels.some(x=>x.label===selected)?`<option value="${esc(selected)}" selected disabled>${esc(selected)}（标签目录中不存在）</option>`:"";return missing+labels.map(x=>`<option value="${esc(x.label)}" ${x.label===selected?"selected":""}>${esc(x.label)}</option>`).join("")}
  function refreshResourceLabelSelects(){$$("select[data-resource-type]").forEach(select=>{const selected=select.value;select.innerHTML=`<option value="">选择资源标签</option>${labelOptions(select.dataset.resourceType,selected)}`})}
  function connectionRow(type,value={}){const n=document.createElement("div");n.className=`repeat-row ${type}`;const common=`<input data-key="name" placeholder="逻辑名" value="${esc(value.name||"")}"><select data-key="resource_label" data-resource-type="${esc(type)}" required><option value="">选择资源标签</option>${labelOptions(type,value.resource_label)}</select><input data-key="host" placeholder="IP / Host" value="${esc(value.host||"")}">`;
    if(type==="telnet")n.innerHTML=common+`<input data-key="port" title="Telnet 端口" type="number" value="${esc(value.port??23)}"><input data-key="baud_rate" title="串口频率/波特率" type="number" value="${esc(value.baud_rate??115200)}"><input data-key="timeout" title="超时秒数" type="number" value="${esc(value.timeout??30)}"><select data-key="shell_mode"><option>auto</option><option>posix</option><option>prompt</option></select><button type="button" class="remove">×</button>`;
    else n.innerHTML=common+`<input data-key="port" type="number" value="${esc(value.port??(type==="ftp"?21:22))}"><input data-key="username" placeholder="用户名" value="${esc(value.username||"root")}"><input data-key="password" type="password" placeholder="密码" value="${esc(value.password||"")}"><input data-key="${type==="ftp"?"timeout":"connect_timeout"}" type="number" value="${esc(value[type==="ftp"?"timeout":"connect_timeout"]??30)}"><button type="button" class="remove">×</button>`;
    n.querySelector(".remove").onclick=()=>n.remove(); return n;
  }
  function addRow(container,type,value){$(container).append(connectionRow(type,value))}
  $("addSsh").onclick=()=>addRow("sshRows","ssh");$("addTelnet").onclick=()=>addRow("telnetRows","telnet");$("addFtp").onclick=()=>addRow("ftpRows","ftp");
  function rows(id){return [...$(id).children].map(row=>Object.fromEntries([...row.querySelectorAll("[data-key]")].map(input=>[input.dataset.key,input.type==="number"?Number(input.value):input.value]))).filter(x=>x.name&&x.host)}
  function blankEnv(){const f=$("environmentForm");f.reset();$("sshRows").innerHTML="";$("telnetRows").innerHTML="";$("ftpRows").innerHTML="";addRow("sshRows","ssh");addRow("telnetRows","telnet");state.selectedEnv=null}
  $("newEnvironment").onclick=blankEnv;
  function editEnv(env){state.selectedEnv=env.name;const f=$("environmentForm");f.name.value=env.name||"";f.title.value=env.title||"";$("sshRows").innerHTML="";$("telnetRows").innerHTML="";$("ftpRows").innerHTML="";Object.entries(env.ssh_hosts||{}).forEach(([name,v])=>addRow("sshRows","ssh",{name,...v}));Object.entries(env.telnet_connections||{}).forEach(([name,v])=>addRow("telnetRows","telnet",{name,...v}));Object.entries(env.ftp_hosts||{}).forEach(([name,v])=>addRow("ftpRows","ftp",{name,...v}));renderEnvs()}
  function objectByName(items){return Object.fromEntries(items.map(({name,...rest})=>[name,rest]))}
  $("environmentForm").onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,nameInput=f.elements.namedItem("name"),titleInput=f.elements.namedItem("title");$("envSaveState").textContent="保存中…";try{const value={name:nameInput.value.trim(),title:titleInput.value.trim(),ssh_hosts:objectByName(rows("sshRows")),telnet_connections:objectByName(rows("telnetRows")),ftp_hosts:objectByName(rows("ftpRows"))};await post("/api/environments",value);$("envSaveState").textContent="已保存";toast("环境 JSON 已保存");await loadEnvs();editEnv(value)}catch(error){$("envSaveState").textContent=`保存失败：${error.message}`;toast(`保存失败：${error.message}`)}};
  function renderEnvs(){$("environmentList").innerHTML=state.envs.length?state.envs.map(env=>`<button class="env-card ${state.selectedEnv===env.name?"active":""}" data-name="${esc(env.name)}"><strong>${esc(env.title||env.name)}</strong><span>${esc(env.name)} · ${Object.keys(env.ssh_hosts||{}).length} 网口 · ${Object.keys(env.telnet_connections||{}).length} 串口</span></button>`).join(""):`<div class="empty">还没有环境档案</div>`;$$('.env-card').forEach(n=>n.onclick=()=>editEnv(state.envs.find(x=>x.name===n.dataset.name)))}
  async function loadEnvs(){state.envs=(await api("/api/environments")).environments;refreshEnvironmentConsumers()}
  async function loadResourceLabels(){const labels=(await api("/api/resource-labels")).resource_labels;if(!Array.isArray(labels)||!labels.length)throw new Error("资源标签目录为空或格式错误");state.resourceLabels=labels;refreshResourceLabelSelects()}

  async function loadScripts(){state.scripts=(await api("/api/scripts")).scripts;$("launchScript").innerHTML=`<option value="">选择脚本</option>`+state.scripts.map(x=>`<option value="${esc(x.name)}">${esc(x.name)} — ${esc(x.description)}</option>`).join("")}
  function resourceChoices(resource){const section=resource.protocol==="telnet"?"telnet_connections":resource.protocol==="ftp"?"ftp_hosts":"ssh_hosts";const choices=[];for(const env of state.envs){for(const [name,value] of Object.entries(env[section]||{})){if(value.resource_label===resource.label)choices.push({environment:env.name,text:`${env.title||env.name} · ${resource.label} · ${value.host} (${name})`})}}return choices}
  function toolResourceOptions(resource,choices=resourceChoices(resource)){return `<option value="">选择包含 ${esc(resource.label)} 的环境</option>`+choices.map(x=>`<option value="${esc(x.environment)}">${esc(x.text)}</option>`).join("")}
  // 环境保存后只更新 state.envs 不足以刷新已经打开的 workflow Tool。定向重建资源下拉框，
  // 避免重新渲染整个 Tool 工作台而丢失用户已填写的参数、采集状态和日志窗口。
  function refreshToolResourceChoices(){const tool=state.tools.find(x=>x.name===state.selectedTool);if(!tool)return;for(const resource of tool.resources||[]){const select=$$("[data-tool-resource]").find(element=>element.dataset.toolResource===resource.name);if(!select)continue;const selected=select.value,choices=resourceChoices(resource);select.innerHTML=toolResourceOptions(resource,choices);if(choices.some(choice=>choice.environment===selected))select.value=selected}}
  function refreshEnvironmentConsumers(){renderEnvs();renderScriptFields();refreshToolResourceChoices()}
  function renderScriptFields(){const script=state.scripts.find(x=>x.name===$("launchScript").value);if(!script){$("resourceFields").innerHTML="";$("packageFields").innerHTML="";$("argumentFields").innerHTML="";return}const resources=script.resources||[];const packageInputs=(script.package_inputs?.length?script.package_inputs:(script.packages||[]).map(name=>({name,alias:name,description:""})));$("resourceFields").innerHTML=resources.length?`<div class="field-group"><span class="field-group-title">连接资源</span>${resources.map(resource=>{const choices=resourceChoices(resource);return `<div class="resource-card"><div class="resource-card-head"><strong>${esc(resource.alias||resource.name)}</strong><span>${esc(resource.protocol.toUpperCase())} · ${esc(resource.label)}</span></div><p>${esc(resource.description||"")}</p><small>脚本绑定名：${esc(resource.name)}</small><label>已注册环境 / 标签资源<select data-resource="${esc(resource.name)}" required><option value="">${choices.length?"请选择环境与对应资源":"没有环境注册了该标签"}</option>${choices.map(x=>`<option value="${esc(x.environment)}">${esc(x.text)}</option>`).join("")}</select></label></div>`}).join("")}</div>`:`<div class="interaction-empty">该脚本未声明 SSH / Telnet / FTP 交互资源</div>`;$("packageFields").innerHTML=packageInputs.length?`<div class="field-group"><span class="field-group-title">HDFS 资源</span>${packageInputs.map(item=>`<div class="resource-card"><div class="resource-card-head"><strong>${esc(item.alias||item.name)}</strong><span>HDFS · ${esc(item.name)}</span></div><p>${esc(item.description||"")}</p><label>包链接<input data-package="${esc(item.name)}" placeholder="留空：使用配置的 link/base_link；填写：指定 HDFS 链接"></label></div>`).join("")}</div>`:`<div class="interaction-empty">该脚本未声明 HDFS 包资源</div>`;$("argumentFields").innerHTML=(script.parameters||[]).map(field=>`<label>${esc(field.label||field.name)}<input data-argument="${esc(field.name)}" ${field.required?"required":""} placeholder="${esc(field.placeholder||"")}"></label>`).join("")}
  $("launchScript").onchange=renderScriptFields;
  function addLine(container,text){const line=document.createElement("div");line.className="line";line.dataset.raw=text;line.innerHTML=esc(text).replace(/(success|completed|verified|ready)/ig,'<span class="ok">$1</span>').replace(/(failed|error|exception)/ig,'<span class="bad">$1</span>').replace(/(warning|timeout)/ig,'<span class="warn">$1</span>').replace(/([A-Za-z]:\\[^\s]+|\/[^\s]+)/g,'<span class="path">$1</span>');container.append(line);container.scrollTop=container.scrollHeight}
  function createTerminal(rows=30,cols=100){return{rows,cols,row:0,col:0,savedRow:0,savedCol:0,escape:false,csi:null,osc:false,oscEsc:false,screen:Array.from({length:rows},()=>Array(cols).fill(" "))}}
  function terminalDimensions(){const element=$("agentConsole"),style=getComputedStyle(element),fontSize=parseFloat(style.fontSize)||12,lineHeight=parseFloat(style.lineHeight)||fontSize*1.7;const canvas=document.createElement("canvas"),context=canvas.getContext("2d");context.font=`${style.fontWeight} ${style.fontSize} ${style.fontFamily}`;const charWidth=context.measureText("M").width||7.2;const innerWidth=element.clientWidth-(parseFloat(style.paddingLeft)||0)-(parseFloat(style.paddingRight)||0),innerHeight=element.clientHeight-(parseFloat(style.paddingTop)||0)-(parseFloat(style.paddingBottom)||0);return{rows:Math.max(2,Math.floor(innerHeight/lineHeight)||30),cols:Math.max(10,Math.floor(innerWidth/charWidth)||100)}}
  function resizeTerminalScreen(rows,cols){const t=state.terminal;if(!t||rows===t.rows&&cols===t.cols)return;if(rows<t.rows){const removed=t.rows-rows;t.screen=t.screen.slice(removed);t.row=Math.max(0,t.row-removed)}else while(t.screen.length<rows)t.screen.push(Array(t.cols).fill(" "));for(const row of t.screen){if(row.length>cols)row.length=cols;else while(row.length<cols)row.push(" ")}t.rows=rows;t.cols=cols;t.row=Math.min(t.row,rows-1);t.col=Math.min(t.col,cols-1);renderTerminal()}
  function renderTerminal(){const t=state.terminal;if(!t)return;const html=t.screen.map((row,index)=>{let end=row.length;while(end>0&&row[end-1]===" ")end--;if(index!==t.row)return esc(row.slice(0,end).join(""));const cursor=Math.max(0,Math.min(t.cols-1,t.col));end=Math.max(end,cursor+1);const value=row.slice(0,end).join("");return `${esc(value.slice(0,cursor))}<span class="terminal-cursor">${esc(value[cursor]||" ")}</span>${esc(value.slice(cursor+1))}`}).join("\n").replace(/\n+$/,"");$("agentConsole").innerHTML=html;$("agentConsole").scrollTop=$("agentConsole").scrollHeight}
  function terminalCsi(t,body,op){const privateMode=body.startsWith("?"),values=body.replace(/^[?!>]/,"").split(";").map(x=>x===""?null:Number(x)),count=values[0]??1,mode=values[0]??0,clamp=()=>{t.row=Math.max(0,Math.min(t.rows-1,t.row));t.col=Math.max(0,Math.min(t.cols-1,t.col))};if(op==="H"||op==="f"){t.row=(values[0]||1)-1;t.col=(values[1]||1)-1}else if(op==="A")t.row-=count;else if(op==="B")t.row+=count;else if(op==="C")t.col+=count;else if(op==="D")t.col-=count;else if(op==="E"){t.row+=count;t.col=0}else if(op==="F"){t.row-=count;t.col=0}else if(op==="G")t.col=count-1;else if(op==="d")t.row=count-1;else if(op==="J"){if(mode===2||mode===3)t.screen=Array.from({length:t.rows},()=>Array(t.cols).fill(" "));else if(mode===1){for(let row=0;row<t.row;row++)t.screen[row].fill(" ");t.screen[t.row].fill(" ",0,t.col+1)}else{t.screen[t.row].fill(" ",t.col);for(let row=t.row+1;row<t.rows;row++)t.screen[row].fill(" ")}}else if(op==="K"){if(mode===1)t.screen[t.row].fill(" ",0,t.col+1);else if(mode===2)t.screen[t.row].fill(" ");else t.screen[t.row].fill(" ",t.col)}else if(op==="P"){t.screen[t.row].splice(t.col,count);while(t.screen[t.row].length<t.cols)t.screen[t.row].push(" ")}else if(op==="@"){t.screen[t.row].splice(t.col,0,...Array(count).fill(" "));t.screen[t.row].length=t.cols}else if(op==="X")t.screen[t.row].fill(" ",t.col,Math.min(t.cols,t.col+count));else if(op==="L"){t.screen.splice(t.row,0,...Array.from({length:count},()=>Array(t.cols).fill(" ")));t.screen.length=t.rows}else if(op==="M"){t.screen.splice(t.row,count);while(t.screen.length<t.rows)t.screen.push(Array(t.cols).fill(" "))}else if(op==="S"){for(let n=0;n<count;n++){t.screen.shift();t.screen.push(Array(t.cols).fill(" "))}}else if(op==="T"){for(let n=0;n<count;n++){t.screen.pop();t.screen.unshift(Array(t.cols).fill(" "))}}else if(op==="s"){t.savedRow=t.row;t.savedCol=t.col}else if(op==="u"){t.row=t.savedRow;t.col=t.savedCol}else if(privateMode&&op==="h"&&values.includes(1049)){t.screen=Array.from({length:t.rows},()=>Array(t.cols).fill(" "));t.row=0;t.col=0}clamp()}
  function terminalWrite(data){const t=state.terminal||(state.terminal=createTerminal());for(const ch of data){if(t.osc){if(ch==="\x07"||(t.oscEsc&&ch==="\\")){t.osc=false;t.oscEsc=false}else t.oscEsc=ch==="\x1b";continue}if(t.csi!==null){if(/[\x40-\x7e]/.test(ch)){terminalCsi(t,t.csi,ch);t.csi=null}else t.csi+=ch;continue}if(t.escape){t.escape=false;if(ch==="[")t.csi="";else if(ch==="]"){t.osc=true;t.oscEsc=false}else if(ch==="7"){t.savedRow=t.row;t.savedCol=t.col}else if(ch==="8"){t.row=t.savedRow;t.col=t.savedCol}continue}if(ch==="\x1b"){t.escape=true;continue}if(ch==="\r"){t.col=0;continue}if(ch==="\n"){t.row++;if(t.row>=t.rows){t.screen.shift();t.screen.push(Array(t.cols).fill(" "));t.row=t.rows-1}continue}if(ch==="\b"){t.col=Math.max(0,t.col-1);continue}if(ch<" ")continue;t.screen[t.row][t.col]=ch;t.col++;if(t.col>=t.cols){t.col=0;t.row++;if(t.row>=t.rows){t.screen.shift();t.screen.push(Array(t.cols).fill(" "));t.row=t.rows-1}}}renderTerminal()}
  async function poll(kind,generation=0){const isRun=kind==="run",cursorKey=isRun?"runCursor":"agentCursor",container=$(isRun?"console":"agentConsole");try{const data=await api(`/api/${kind}/events?cursor=${state[cursorKey]}`);if(!isRun&&(generation!==state.agentPollGeneration||data.generation!==state.agentSessionGeneration))return;state[cursorKey]=data.next;for(const event of data.events){if(event.type==="output")addLine(container,event.text);if(event.type==="terminal")terminalWrite(event.data);if(event.type==="complete"){if(isRun)addLine(container,`[${event.success?"SUCCESS":"FAILED"}] ${event.status}`);else{state.agentRunning=false;terminalWrite(`\r\n[${event.success?"SUCCESS":"FAILED"}] ${event.status}\r\n`)}return}}state[isRun?"runTimer":"agentTimer"]=setTimeout(()=>poll(kind,generation),60)}catch(error){if(!isRun&&generation!==state.agentPollGeneration)return;if(isRun)addLine(container,`BRIDGE ERROR: ${error.message}`);else{state.agentRunning=false;terminalWrite(`\r\nBRIDGE ERROR: ${error.message}\r\n`)}}}
  $("launchForm").onsubmit=async e=>{e.preventDefault();const packages=Object.fromEntries($$("[data-package]").map(n=>[n.dataset.package,n.value.trim()?{path_override:n.value.trim()}:{}]));const environments=Object.fromEntries($$("[data-resource]").map(n=>[n.dataset.resource,{environment:n.value}]));const arguments_=Object.fromEntries($$("[data-argument]").map(n=>[n.dataset.argument,n.value]));const request={script:$("launchScript").value,mode:$("launchMode").value,environments,parameters:{packages,arguments:arguments_}};$("console").innerHTML="";state.runCursor=0;await post("/api/run/start",request);poll("run")};
  $("stopRun").onclick=()=>post("/api/run/stop",{});$("openLog").onclick=()=>post("/api/open",{target:"log"}).catch(e=>toast(e.message));$("openRun").onclick=()=>post("/api/open",{target:"run"}).catch(e=>toast(e.message));$("clearConsole").onclick=()=>$("console").innerHTML="";$("consoleFilter").oninput=e=>$$('#console .line').forEach(n=>n.classList.toggle("hidden",!n.dataset.raw.toLowerCase().includes(e.target.value.toLowerCase())));

  async function loadTools(){state.tools=(await api("/api/tools")).tools;renderToolNav();if(state.tools[0])await selectTool(state.tools[0].name)}
  function renderToolNav(){$("toolNav").innerHTML=state.tools.map(x=>`<button class="tool-link ${x.name===state.selectedTool?"active":""}" data-name="${esc(x.name)}"><strong>${esc(x.title)}</strong><span>${esc(x.description)}</span></button>`).join("");$$('.tool-link').forEach(n=>n.onclick=()=>selectTool(n.dataset.name))}
  function toolControl(field){const a=`data-name="${esc(field.name)}" ${field.required?"required":""}`;if(field.type==="textarea")return `<textarea ${a} placeholder="${esc(field.placeholder||"")}">${esc(field.default||"")}</textarea>`;if(field.type==="select")return `<select ${a}>${(field.options||[]).map(option=>`<option value="${esc(typeof option==="object"?option.value:option)}">${esc(typeof option==="object"?option.label:option)}</option>`).join("")}</select>`;if(field.type==="checkbox")return `<input ${a} type="checkbox" ${field.default?"checked":""}>`;return `<input ${a} type="${esc(field.type||"text")}" value="${esc(field.default||"")}" placeholder="${esc(field.placeholder||"")}">`}
  function clearLogFindTimers(){Object.values(state.logFindTimers).forEach(clearTimeout);state.logFindTimers={}}
  async function selectTool(name){state.selectedTool=name;renderToolNav();const tool=state.tools.find(x=>x.name===name);if(tool.kind==="workflow"&&tool.renderer==="log_collection")return renderLogTool(tool);$("toolStage").innerHTML=`<span class="kicker">DYNAMIC PYTHON TOOL</span><h2>${esc(tool.title)}</h2><p class="muted">${esc(tool.description)}</p><form class="tool-form" id="activeToolForm">${tool.fields.map(field=>`<label>${esc(field.label||field.name)}${toolControl(field)}</label>`).join("")}<button class="primary">运行工具</button></form><pre class="tool-result" id="toolResult">等待执行</pre>`;$("activeToolForm").onsubmit=async e=>{e.preventDefault();const values=Object.fromEntries([...e.currentTarget.querySelectorAll("[data-name]")].map(n=>[n.dataset.name,n.type==="checkbox"?n.checked:n.type==="number"?Number(n.value):n.value]));try{$("toolResult").textContent=JSON.stringify((await post("/api/tools/run",{name,values})).result,null,2)}catch(error){$("toolResult").textContent=`ERROR: ${error.message}`}}}

  async function renderLogTool(tool){clearTimeout(state.toolTimer);clearLogFindTimers();state.logPanes=[];state.logFinds=[];state.logContexts=[];state.logQueryTokens=[];const resources=(tool.resources||[]).map(resource=>`<label>${esc(resource.alias||resource.name)}<select data-tool-resource="${esc(resource.name)}" required>${toolResourceOptions(resource)}</select></label>`).join("");$("toolStage").innerHTML=`<span class="kicker">WORKFLOW TOOL</span><h2>${esc(tool.title)}</h2><p class="muted">${esc(tool.description)}</p><div class="log-workbench"><form class="tool-form log-collect-form" id="activeToolForm">${resources}${tool.fields.map(field=>`<label>${esc(field.label||field.name)}${toolControl(field)}</label>`).join("")}<div class="actions"><button class="danger" type="button" id="stopTool">停止</button><button class="primary">获取日志</button></div></form><div class="tool-progress" id="toolProgress" hidden><div><span id="toolProgressLabel">SCP</span><strong id="toolProgressText">0 / 0</strong></div><progress id="toolProgressBar" max="1" value="0"></progress></div><div class="log-task-console" id="toolResult">等待采集</div><div class="log-query-bar"><label>本地批次<select id="logBatch"></select></label><label>日期（需配合时间）<input id="logDate" type="date"></label><label>中心时间（留空按文件浏览）<input id="logTime" type="time" step="1"></label><label>窗口（分钟）<input id="logWindow" type="number" min="1" max="1440" value="60"></label><button class="ghost" id="refreshBatches" type="button">刷新批次</button><button class="primary" id="addLogPane" type="button">＋ 日志窗口</button></div><div class="log-panes" id="logPanes"></div></div>`;$("activeToolForm").onsubmit=e=>startWorkflowTool(e,tool);$("stopTool").onclick=()=>post("/api/tools/workflow/stop",{}).catch(error=>toast(error.message));$("refreshBatches").onclick=loadLogBatches;$("logBatch").onchange=async e=>{clearLogFindTimers();state.selectedLogBatch=e.target.value;state.logPanes=[];state.logFinds=[];state.logContexts=[];state.logQueryTokens=[];await loadLogTargets();if(state.logTargets.length){state.logPanes=[state.logTargets[0]];state.logFinds=[""];state.logContexts=[3];state.logQueryTokens=[0]}renderLogPanes();queryAllLogPanes()};["logDate","logTime","logWindow"].forEach(id=>$(id).onchange=()=>queryAllLogPanes());$("addLogPane").onclick=()=>{if(!state.logTargets.length)return toast("该批次没有目标日志");state.logPanes.push(state.logTargets[Math.min(state.logPanes.length,state.logTargets.length-1)]);state.logFinds.push("");state.logContexts.push(3);state.logQueryTokens.push(0);renderLogPanes();queryAllLogPanes()};await loadLogBatches()}

  async function startWorkflowTool(event,tool){event.preventDefault();const form=event.currentTarget,arguments_=Object.fromEntries([...form.querySelectorAll("[data-name]")].map(n=>[n.dataset.name,n.type==="number"?Number(n.value):n.value]));const environments=Object.fromEntries([...form.querySelectorAll("[data-tool-resource]")].map(n=>[n.dataset.toolResource,{environment:n.value}]));$("toolResult").textContent="启动采集…";$("toolProgress").hidden=true;$("toolProgressBar").value=0;state.toolCursor=0;clearTimeout(state.toolTimer);try{const started=await post("/api/tools/workflow/start",{tool:tool.name,environments,parameters:{arguments:arguments_}});state.toolGeneration=started.generation;pollWorkflowTool(started.generation)}catch(error){$("toolResult").textContent=`ERROR: ${error.message}`}}

  function updateToolProgress(event){const root=$("toolProgress"),bar=$("toolProgressBar"),label=$("toolProgressLabel"),text=$("toolProgressText");if(!root||!bar||!label||!text)return;const total=Math.max(1,Number(event.total)||1),completed=Math.max(0,Math.min(total,Number(event.completed)||0)),percent=Math.floor(completed*100/total);root.hidden=false;label.textContent=`SCP · ${event.operation_id}`;text.textContent=`${completed} / ${event.total} · ${percent}%`;bar.max=total;bar.value=completed}

  async function pollWorkflowTool(generation){try{const data=await api(`/api/tools/workflow/events?cursor=${state.toolCursor}`);if(generation!==state.toolGeneration||data.generation!==generation)return;state.toolCursor=data.next;for(const event of data.events){if(event.type==="output")$("toolResult").textContent+=`\n${event.text}`;if(event.type==="progress")updateToolProgress(event);if(event.type==="complete"){$("toolResult").textContent+=`\n[${event.success?"SUCCESS":"FAILED"}] ${event.status}`;if(event.success)await loadLogBatches();return}}state.toolTimer=setTimeout(()=>pollWorkflowTool(generation),100)}catch(error){$("toolResult").textContent+=`\nBRIDGE ERROR: ${error.message}`}}

  async function loadLogBatches(){const element=$("logBatch");if(!element)return;state.logBatches=(await api("/api/log-batches")).batches;if(!state.selectedLogBatch||!state.logBatches.some(x=>x.batch_id===state.selectedLogBatch))state.selectedLogBatch=state.logBatches[0]?.batch_id||"";element.innerHTML=state.logBatches.length?state.logBatches.map(x=>`<option value="${esc(x.batch_id)}" ${x.batch_id===state.selectedLogBatch?"selected":""}>${esc(x.alias)} · ${esc(x.collected_at)} · ${esc(x.batch_id)} · ${x.record_count} 行</option>`).join(""):`<option value="">尚无已完成批次</option>`;await loadLogTargets();if(state.logTargets.length&&!state.logPanes.length){state.logPanes=[state.logTargets[0]];state.logFinds=[""];state.logContexts=[3];state.logQueryTokens=[0]}renderLogPanes();queryAllLogPanes()}

  async function loadLogTargets(){state.logTargets=state.selectedLogBatch?(await api(`/api/log-batches/targets?batch=${encodeURIComponent(state.selectedLogBatch)}`)).targets:[];const panes=[],finds=[],contexts=[];state.logPanes.forEach((target,index)=>{if(state.logTargets.includes(target)){panes.push(target);finds.push(state.logFinds[index]||"");contexts.push(Number.isInteger(state.logContexts[index])?state.logContexts[index]:3)}});state.logPanes=panes;state.logFinds=finds;state.logContexts=contexts;state.logQueryTokens=panes.map(()=>0)}

  function renderLogPanes(){const root=$("logPanes");if(!root)return;root.innerHTML=state.logPanes.map((target,index)=>`<section class="log-pane" data-pane="${index}"><header><select data-pane-target="${index}">${state.logTargets.map(x=>`<option value="${esc(x)}" ${x===target?"selected":""}>${esc(x)}</option>`).join("")}</select><input class="log-find" data-pane-find="${index}" value="${esc(state.logFinds[index]||"")}" maxlength="200" placeholder="Find 关键词（筛选整个日志）"><label class="log-context-control">上下 <input data-pane-context="${index}" type="number" min="0" max="50" step="1" value="${esc(state.logContexts[index]??3)}"> 行</label><button class="remove" data-remove-pane="${index}" type="button">×</button></header><div class="log-records" id="logRecords${index}">加载中…</div><footer><button class="ghost small" data-prev-page="${index}" type="button">上一页</button><span id="logPage${index}">1</span><button class="ghost small" data-next-page="${index}" type="button">下一页</button></footer></section>`).join("");$$('[data-pane-target]').forEach(n=>n.onchange=()=>{state.logPanes[Number(n.dataset.paneTarget)]=n.value;queryLogPane(Number(n.dataset.paneTarget),1)});$$('[data-pane-find]').forEach(n=>n.oninput=()=>{const index=Number(n.dataset.paneFind);state.logFinds[index]=n.value;clearTimeout(state.logFindTimers[index]);state.logFindTimers[index]=setTimeout(()=>queryLogPane(index,1),180)});$$('[data-pane-context]').forEach(n=>n.onchange=()=>{const index=Number(n.dataset.paneContext),value=Math.max(0,Math.min(50,Math.trunc(Number(n.value)||0)));n.value=String(value);state.logContexts[index]=value;queryLogPane(index,1)});$$('[data-remove-pane]').forEach(n=>n.onclick=()=>{clearLogFindTimers();const index=Number(n.dataset.removePane);state.logPanes.splice(index,1);state.logFinds.splice(index,1);state.logContexts.splice(index,1);state.logQueryTokens.splice(index,1);renderLogPanes();queryAllLogPanes()});$$('[data-prev-page]').forEach(n=>n.onclick=()=>queryLogPane(Number(n.dataset.prevPage),Math.max(1,Number($(`logPage${n.dataset.prevPage}`).dataset.page||1)-1)));$$('[data-next-page]').forEach(n=>n.onclick=()=>queryLogPane(Number(n.dataset.nextPage),Number($(`logPage${n.dataset.nextPage}`).dataset.page||1)+1))}

  function queryAllLogPanes(){if($("logDate")?.value&&!$("logTime")?.value)return toast("按日期查询时必须填写中心时间");state.logPanes.forEach((_target,index)=>queryLogPane(index,1))}

  function markKeyword(value,keyword){const text=String(value??""),needle=String(keyword??"").trim();if(!needle)return esc(text);const folded=text.toLocaleLowerCase(),wanted=needle.toLocaleLowerCase();let cursor=0,html="",found;while((found=folded.indexOf(wanted,cursor))!==-1){html+=esc(text.slice(cursor,found))+`<mark>${esc(text.slice(found,found+needle.length))}</mark>`;cursor=found+needle.length}return html+esc(text.slice(cursor))}

  async function queryLogPane(index,page){
    if(!$(`logRecords${index}`)||!state.selectedLogBatch)return;
    const token=++state.logQuerySerial;state.logQueryTokens[index]=token;
    const params=new URLSearchParams({batch:state.selectedLogBatch,target:state.logPanes[index],page:String(page),limit:"200",date:$("logDate").value,time:$("logTime").value,window:$("logWindow").value||"60",keyword:state.logFinds[index]||"",context:String(state.logContexts[index]??3)});
    try{
      const data=await api(`/api/log-batches/query?${params}`),keyword=data.keyword||"";
      if(state.logQueryTokens[index]!==token)return;
      // 查询返回时日志面板可能已被切换或重建，必须重新取得当前 DOM。分页按钮只有
      // data 属性而没有 id，不能交给基于 getElementById() 的 $() 查询。
      const container=$(`logRecords${index}`),pageLabel=$(`logPage${index}`),previous=document.querySelector(`[data-prev-page="${index}"]`),next=document.querySelector(`[data-next-page="${index}"]`);
      if(!container||!pageLabel||!previous||!next)return;
      container.innerHTML=data.records.length?data.records.map(row=>`<button class="log-row ${row.clock_seconds===null?"unknown-time":""} ${row.find_role?`find-${row.find_role}`:""}" data-clock="${row.clock_seconds??""}" data-date="${esc(row.date_key||"")}"><time>[${esc(row.timestamp)}]</time><span>${row.find_role==="match"?markKeyword(row.text,keyword):esc(row.text)}</span><small>${esc(row.source_file)}:${row.source_line}</small></button>`).join(""):`<div class="interaction-empty">没有匹配记录</div>`;
      pageLabel.textContent=keyword?`${data.page} / ${Math.max(1,Math.ceil(data.total/data.limit))} · ${data.total} 个命中 · 本页 ${data.returned_count} 行`:`${data.page} / ${Math.max(1,Math.ceil(data.total/data.limit))} · ${data.total} 条`;pageLabel.dataset.page=String(data.page);previous.disabled=data.page<=1;next.disabled=!data.has_more;
      $$(`#logRecords${index} .log-row`).forEach(row=>row.onclick=()=>highlightRelated(row));
    }catch(error){const container=$(`logRecords${index}`);if(state.logQueryTokens[index]===token&&container)container.textContent=`ERROR: ${error.message}`}
  }

  function highlightRelated(selected){$$('.log-row').forEach(row=>row.classList.remove("selected","correlated"));selected.classList.add("selected");if(selected.dataset.clock==="")return;const selectedClock=Number(selected.dataset.clock),selectedDate=selected.dataset.date;$$('.log-row').forEach(row=>{if(row===selected||row.dataset.clock==="")return;const clock=Number(row.dataset.clock),rowDate=row.dataset.date;let distance;if(selectedDate&&rowDate){const left=new Date(`${selectedDate}T00:00:00Z`).getTime()/1000+selectedClock,right=new Date(`${rowDate}T00:00:00Z`).getTime()/1000+clock;distance=Math.abs(left-right)}else{const direct=Math.abs(selectedClock-clock);distance=Math.min(direct,86400-direct)}if(distance<=300)row.classList.add("correlated")})}

  async function loadSettings(){const s=await api("/api/settings");$("uploadDir").value=s.upload_dir||"";$("agentCommand").value=s.agent_command??"codeagent";$("agentCwd").value=s.agent_cwd||""}
  $("agentSettings").onclick=()=>$("settingsPanel").classList.toggle("open");$("saveSettings").onclick=async()=>{try{await post("/api/settings",{upload_dir:$("uploadDir").value,agent_command:$("agentCommand").value,agent_cwd:$("agentCwd").value});toast("Agent 设置已保存")}catch(error){toast(error.message)}};
  let agentInputTail=Promise.resolve();function sendAgentInput(value){const task=agentInputTail.then(()=>post("/api/agent/input",{value}));agentInputTail=task.catch(()=>{});return task}
  function clipboardName(file,index){if(file.name)return file.name;const extension={"image/png":"png","image/jpeg":"jpg","image/gif":"gif","image/webp":"webp"}[file.type]||"bin";return `clipboard-${Date.now()}-${index+1}.${extension}`}
  async function saveFiles(files){const paths=[];for(const [index,file] of [...files].entries()){const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)});const saved=await post("/api/upload",{name:clipboardName(file,index),data});paths.push(saved.path)}return paths}
  const quoteTerminalPath=path=>`"${String(path).replace(/"/g,'\\"')}"`;
  async function insertFiles(files){const paths=await saveFiles(files);if(!paths.length)return;const reference=paths.map(quoteTerminalPath).join(" ");try{await sendAgentInput(reference)}catch(error){terminalWrite(`\r\n[FILES SAVED] ${reference}\r\n`);throw error}$("agentConsole").focus();toast(`${paths.length} 个文件已保存，路径已插入`)}
  $("chooseAgentFiles").onclick=()=>$("agentFiles").click();$("agentFiles").onchange=e=>{insertFiles(e.target.files).catch(x=>toast(x.message));e.target.value=""};
  const terminal=$("agentConsole");terminal.onclick=()=>terminal.focus();["dragenter","dragover"].forEach(type=>terminal.addEventListener(type,e=>{e.preventDefault();if(e.dataTransfer)e.dataTransfer.dropEffect="copy";terminal.classList.add("drag")}));["dragleave","drop"].forEach(type=>terminal.addEventListener(type,e=>{e.preventDefault();terminal.classList.remove("drag")}));terminal.addEventListener("drop",e=>insertFiles(e.dataTransfer.files).catch(x=>toast(x.message)));
  let agentResizeTimer=null;new ResizeObserver(()=>{clearTimeout(agentResizeTimer);agentResizeTimer=setTimeout(()=>{if(!state.agentRunning)return;const size=terminalDimensions();if(state.terminal&&size.rows===state.terminal.rows&&size.cols===state.terminal.cols)return;resizeTerminalScreen(size.rows,size.cols);post("/api/agent/resize",size).catch(error=>toast(error.message))},120)}).observe(terminal);
  terminal.onpaste=e=>{const itemFiles=[...(e.clipboardData?.items||[])].filter(item=>item.kind==="file").map(item=>item.getAsFile()).filter(Boolean);const files=itemFiles.length?itemFiles:[...(e.clipboardData?.files||[])];if(files.length){e.preventDefault();insertFiles(files).catch(x=>toast(x.message));return}const value=e.clipboardData?.getData("text/plain")||"";if(value){e.preventDefault();sendAgentInput(value).catch(error=>toast(error.message))}};
  $("agentStart").onclick=async()=>{clearTimeout(state.agentTimer);const generation=++state.agentPollGeneration;try{$("agentConsole").textContent="";const size=terminalDimensions();state.terminal=createTerminal(size.rows,size.cols);renderTerminal();state.agentCursor=0;const started=await post("/api/agent/start",{command:$("agentCommand").value,cwd:$("agentCwd").value,rows:size.rows,cols:size.cols});state.agentSessionGeneration=started.generation;state.agentRunning=true;poll("agent",generation);terminal.focus()}catch(error){state.agentRunning=false;toast(error.message)}};$("agentStop").onclick=()=>{clearTimeout(state.agentTimer);state.agentPollGeneration++;state.agentRunning=false;return post("/api/agent/stop",{}).catch(error=>toast(error.message))};
  terminal.onkeydown=e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="v")return;const keys={Enter:"\r",Backspace:"\x7f",Tab:e.shiftKey?"\x1b[Z":"\t",Escape:"\x1b",ArrowUp:"\x1b[A",ArrowDown:"\x1b[B",ArrowRight:"\x1b[C",ArrowLeft:"\x1b[D",Home:"\x1b[H",End:"\x1b[F",PageUp:"\x1b[5~",PageDown:"\x1b[6~",Insert:"\x1b[2~",Delete:"\x1b[3~",F1:"\x1bOP",F2:"\x1bOQ",F3:"\x1bOR",F4:"\x1bOS",F5:"\x1b[15~",F6:"\x1b[17~",F7:"\x1b[18~",F8:"\x1b[19~",F9:"\x1b[20~",F10:"\x1b[21~",F11:"\x1b[23~",F12:"\x1b[24~"};let value=keys[e.key];if(!value&&e.ctrlKey&&/^[a-z]$/i.test(e.key))value=String.fromCharCode(e.key.toUpperCase().charCodeAt(0)-64);if(!value&&!e.ctrlKey&&!e.altKey&&!e.metaKey&&!e.isComposing&&e.key.length===1)value=e.key;if(value){e.preventDefault();sendAgentInput(value).catch(error=>toast(error.message))}};

  async function initialize(){await api("/api/health");await loadResourceLabels();blankEnv();await Promise.all([loadEnvs(),loadScripts(),loadSettings()]);await loadTools();$("health").textContent="LOCAL BRIDGE ONLINE"}
  initialize().catch(error=>{$("health").textContent="BRIDGE ERROR";toast(error.message)});
})();
